name: Docs build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  check_source:
    name: "Check source for changes"
    runs-on: ubuntu-latest
    outputs:
      run_build: ${{ steps.check.outputs.run_build }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check for source changes
        id: check
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD
          
          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file != src/* ]]; then
              echo "This modified file is not under the 'src' folder."
              echo "::set-output name=run_build::false"
              break
            else
              echo "::set-output name=run_build::true"
            fi
          done < files.txt

  build:
    runs-on: ubuntu-latest
    needs: check_source
    if: needs.check_source.outputs.run_build == 'true'

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install markdown

      - name: Build docs
        run: python3 .github/workflows/docs-build.py
    
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic documentation build
